/* Generated By:JavaCC: Do not edit this line. CompilateurConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilateurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PERIODIC = 8;
  /** RegularExpression Id. */
  int APERIODIC = 9;
  /** RegularExpression Id. */
  int FIRST = 10;
  /** RegularExpression Id. */
  int BOTH = 11;
  /** RegularExpression Id. */
  int PRIORITY = 12;
  /** RegularExpression Id. */
  int MEMORY = 13;
  /** RegularExpression Id. */
  int RENDERING = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int ID = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\" \"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"Periodic\"",
    "\"Aperiodic\"",
    "\"First\"",
    "\"Both\"",
    "\"Priority\"",
    "\"Memory\"",
    "\"Rendering\"",
    "<INT>",
    "<ID>",
    "\"=\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"->\"",
  };

}
